version: '2'

volumes:
  nextcloud:
  # db:

services:
  # db:
  #   image: mariadb
  #   command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   restart: always
  #   volumes:
  #     - db:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=DsixCikbx8RT6gX7UFXHrA==
  #     - MYSQL_PASSWORD=ouMl9/HdcOUIEa1qQOsRYA==
  #     - MYSQL_DATABASE=nextcloud
  #     - MYSQL_USER=nextcloud
  app:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
      - $PWD/config/config.php:/var/www/html/config/config.php
    ports:
      - 8080:80

  # web:
  #   image: nginx:alpine
  #   volumes:
  #     - $PWD/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - nextcloud:/var/www/html
  #   ports:
  #     - 8080:80
  #   links:
  #     - db
  #     - app
  #   restart: always